'use client'
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { Toaster } from "@/components/ui/sonner"
import { AppContext } from "@/contexts";
import Navbar from "@/components/Navbar";
import { usePathname } from "next/navigation";
import { checkIsPublicRoute } from "@/functions/checkIsPublicRoute";
import { PrivateRoute } from "@/components/PrivateRoute";

const inter = Inter({ subsets: ["latin"] });

/*export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};*/

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const pathname = usePathname();

  const isPublicPage = checkIsPublicRoute(pathname!)

  return (
    <html lang="en" className="h-full" >
      <head>
        <title>Agendify</title>
      </head>
      <body className={inter.className + "bg-[#F1FFFD]"}>
        <main className="relative flex flex-col min-h-screen" >
          <AppContext>
            <Navbar />
            <div className="flex-grow flex-1">
              {isPublicPage && children}
              {!isPublicPage && <PrivateRoute>{children}</PrivateRoute>}
            </div>
          </AppContext>
        </main>
      </body>
      <Toaster />
    </html>
  );
}
