import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { Toaster } from "@/components/ui/sonner"
import { AppContext } from "@/contexts";
import Navbar from "@/components/Navbar";


const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="h-full" >
      <body className={inter.className + "bg-[#F1FFFD]"}>
        <main className="relative flex flex-col min-h-screen" >
          <AppContext>
            <Navbar />
            <div className="flex-grow flex-1">{children}</div>
          </AppContext>
        </main>
      </body>
      <Toaster />
    </html>
  );
}
